### ISSUE TITLE
Highlight post - improvement and issue

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#30]
Now highlighted posts look:
![image](https://user-images.githubusercontent.com/778890/34480385-703835a6-efac-11e7-8290-e77d068df0b4.png)

You can see, that the css class for highlighting is assigned to the "post rate box" and the post content. It should be much better to add this class only to the whole post.

There is a code:
`find_replace_templatesets("postbit","#".preg_quote('<div class="post {$unapproved_shade}" style="{$post_visibility}" id="post_{$post[\'pid\']}">')."#i","<div class=\"post{\$post['styleclass']} {\$unapproved_shade}\" style=\"{\$post_visibility}\" id=\"post_{\$post['pid']}\">");
find_replace_templatesets("postbit_classic","#".preg_quote('<div class="post classic {$unapproved_shade}" style="{$post_visibility}" id="post_{$post[\'pid\']}">')."#i","<div class=\"post{\$post['styleclass']} {\$unapproved_shade}\" style=\"{\$post_visibility}\" id=\"post_{\$post['pid']}\">");`

And then if the post get X emoji reactions, then add this as a CSS class
`$post['styleclass'] = ' popular_post';`

CSS class popular_post:
`.popular_post{
border: 2px solid;
border-radius: 3px;
border-color: rgba(112,202,47,0.5);
background-color: rgba(139,195,74,0.3);
}`

Here is the output:
![image](https://user-images.githubusercontent.com/778890/34480754-7e6aaf9e-efae-11e7-903c-1a601b4f5cff.png)

Just keep in mind - add ajax for post highlighting feature, when the post gets X amount of required reaction -> highlight it immediately without refreshing

**Comment by WhiteNeo** [comment]
Yes it will be improved in the next version, thanks for the feedback :)

**Comment by Eldenroot** [comment]
I am looking forward :)

**Comment by Eldenroot** [comment]
@WhiteNeo - one more thing - use different css class for member profile - it is "highlighted", is it supposed to be or is it a bug?

![image](https://user-images.githubusercontent.com/778890/34488715-d3aa5722-efd9-11e7-8853-663fc95ab4a6.png)

**Comment by WhiteNeo** [comment]
Due all is inside templates and templates load this parts i have to work on it :)

But i think it is a bug i will add now the fix :)

**Comment by WhiteNeo** [comment]
Ok it is fixed i add the latest file a few minutes ago :)

Let me know.

**Comment by Eldenroot** [comment]
@WhiteNeo - it is not fixed :( Same issue, css class is still used for emoji box and for post content, NOT for the whole post.

![image](https://user-images.githubusercontent.com/778890/34578216-6ba0f3fa-f184-11e7-9006-a512885610f9.png)
